spring:
  application:
    name: School

  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    username: schooluser
    password: rubay
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect